### ISSUE TITLE
Cannot find module 'ionic-angular/gestures/gesture'

### ISSUE THREAD

**Issue by va0000ll** [wbhob/ionic-long-press#20]
I it should be `import { Gesture } from '@ionic/core';` in ionic 4

**Comment by wbhob** [comment]
PR?

**Comment by bleuscyther** [comment]
I tried to update the packages but when i test : 
`Module not found: Error: Can't resolve 'ionic-long-press' in  ....`

I wasn t able to produce a valid pull request

**Comment by wbhob** [comment]
This sounds like a node/npm problem, not a package problem.

**Comment by olivermuc** [comment]
Getting the same error with `ionic v4.11.3`, followed instructions step by step.

**Comment by wbhob** [comment]
I'm open to a PR to fix this - I will gladly merge and publish it

**Comment by Enteee** [comment]
bumping dependencies fixed this for me, see pr #22 .

**Comment by wbhob** [comment]
Looks like ng-packagr is also working on a new version to support TS ^3.6 so I'll update as well when that comes out. currently working on pushing 2.0.2 of this library

**Comment by wbhob** [comment]
ok folks its published. give it a shot and re-open an issue if it persists.
